package com.desafio.test.exceptions;

public class InvalidMathematicalOperationResultException extends Throwable {
    public InvalidMathematicalOperationResultException(String message) {
        super(message);
    }
}
